### ISSUE TITLE
The command you used to run the container

### ISSUE THREAD

**Issue by sunilkumarpvns** [bitnami/bitnami-docker-pgbouncer#12]
Hi team,

1)I used below command to run docker container.

              docker run -p 6432:6432 -e POSTGRESQL_PASSWORD=welcome01 -e POSTGRESQL_HOST=10.184.40.90 -e POSTGRESQL_PORT=5432 -e PGBOUNCER_PORT=6432 -e PGBOUNCER_AUTH_TYPE=plain -e PGBOUNCER_IGNORE_STARTUP_PARAMETERS=extra_float_digits -e PGBOUNCER_SERVER_IDLE_TIMEOUT=10 -e PGBOUNCER_SERVER_CONNECT_TIMEOUT=10 -e PGBOUNCER_CLIENT_IDLE_TIMEOUT=10 -e PGBOUNCER_IDLE_TRANSACTION_TIMEOUT=10 -e PGBOUNCER_MAX_DB_CONNECTIONS=200 -e PGBOUNCER_MAX_USER_CONNECTIONS=200 -e PGBOUNCER_MAX_CLIENT_CONN=200 pgbouncer

2)in command i put max_client_conn to 200 but in log i can see max_client_conn 100.

                       "2021-08-10 05:18:07.093 UTC [1] LOG kernel file descriptor limit: 1048576 (hard: 1048576); max_client_conn: 100, max expected fd use: 152"

3)i put idle _timeout to 10 sec but  connections are closing after 300 secs.

please help me how i can put idle time for connectionn to 10 sec

**Comment by migruiz4** [comment]
Hi @sunilkumarpvns,

I'm sorry but the following environment variables you used are not supported by the `bitnami/pgbouncer` image:

- `PGBOUNCER_SERVER_IDLE_TIMEOUT`
- `PGBOUNCER_SERVER_CONNECT_TIMEOUT`
- `PGBOUNCER_CLIENT_IDLE_TIMEOUT`
- `PGBOUNCER_IDLE_TRANSACTION_TIMEOUT`
- `PGBOUNCER_MAX_DB_CONNECTIONS`
- `PGBOUNCER_MAX_USER_CONNECTIONS`
- `PGBOUNCER_MAX_CLIENT_CONN`

If you'd like to configure those settings, you may need to mount your configuration file (`pgbouncer.ini`) using:
 
```
-v /host/path/to/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
```

Alternatively, if you'd like to configure those pgbouncer settings using environment variables, feel free to send a PR with the necessary changes and we will be happy to review it and help with anything you need.
