### ISSUE TITLE
add ENV variables for pool_mode, default_pool_size, max_client_conn

### ISSUE THREAD

**Issue by masterkain** [bitnami/bitnami-docker-pgbouncer#14]
hello,
I found it weird there were no ENV variables for the settings above, which is one of the reasons a user tries out pgbouncer in first place.

are we interested in having those?

**Comment by migruiz4** [comment]
Hi @masterkain,

Our pgbouncer image doesn't have support to configure some settings using environment variables, but it would be possible to mount your configuration file (`pgbouncer.ini`) using:
```
-v /host/path/to/pgbouncer.ini:/bitnami/pgbouncer/conf/pgbouncer.ini
```

If you'd like to configure those pgbouncer settings using environment variables, feel free to send a PR with the necessary changes and we will be happy to review it and help with anything you need.

As a reference, you could take a look at the following contribution https://github.com/bitnami/bitnami-docker-pgbouncer/pull/13

**Comment by tybritten** [comment]
https://github.com/bitnami/bitnami-docker-pgbouncer/pull/15

I can add default_pool_size to this PR if you'd like

**Comment by tybritten** [comment]
ok i added `default_pool_size`

**Comment by migruiz4** [comment]
That is awesome @tybritten! Thank you very much for your contribution!

**Comment by migruiz4** [comment]
PR #15 was merged adding the additional Pgpool env parameters. Closing this issue.
