### ISSUE TITLE
Using with Bitnami PostgreSQL Helm chart

### ISSUE THREAD

**Issue by khssnv** [bitnami/bitnami-docker-pgbouncer#2]
Hello there! What the best way to use this with the [Bitnami PostgreSQL Helm chart](https://artifacthub.io/packages/helm/bitnami/postgresql)? Thanks!

**Comment by carrodher** [comment]
Hi, Bitnami also provides [Bitnami PostgreSQL HA Helm Chart](https://artifacthub.io/packages/helm/bitnami/postgresql-ha) that, among other features, includes pgpool to the cluster, not sure if this can be a valid solution for you. About the specific case of pgbouncer in the Helm Chart, we don't have plans for adding it in the short term although we will be happy to review any contribution adding this kind of features.

**Comment by khssnv** [comment]
Ok, thank you @carrodher.
