### ISSUE TITLE
Regression- Previous PR #19 got Clobbered

### ISSUE THREAD

**Issue by tybritten** [bitnami/bitnami-docker-pgbouncer#21]
After https://github.com/bitnami/bitnami-docker-pgbouncer/pull/19 got merged, the build for r75 overwrote the changes so they got lost and are gone. Needs to be reverted.

**Comment by tybritten** [comment]
Any update?

**Comment by yilmi** [comment]
Hi @tybritten, apologies for the delay, we're still working on this and want to make sure this doesn't happen, thanks.

**Comment by Mauraza** [comment]
Hi @tybritten,

the change should appear by now. 
https://github.com/bitnami/bitnami-docker-pgbouncer/blob/54c3ca22671dadd29caa6f6d4fe6da1b829e9cf1/1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L257-L258

**Comment by tybritten** [comment]
it's weird. If i click on your link, its there. If I go directly to that commit (https://github.com/bitnami/bitnami-docker-pgbouncer/blob/54c3ca22671dadd29caa6f6d4fe6da1b829e9cf1/1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh) its the old version, and that's what's in the r89n container

**Comment by tybritten** [comment]
the changes here https://github.com/bitnami/bitnami-docker-pgbouncer/blob/54c3ca22671dadd29caa6f6d4fe6da1b829e9cf1/1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L97-L114 are still missing
https://github.com/bitnami/bitnami-docker-pgbouncer/commit/f28c6d8eacf2bfd8c3e3caae9d2148a1c6a1cb73#diff-92796553d16baf5da7ea09a67b7e91e3dcbdb2a439db875463e06a213d2c9039

**Comment by Mauraza** [comment]
Hi @tybritten,

These part
```bash
    if [[ -n "$PGBOUNCER_SERVER_TLS_CA_FILE" ]]; then
        warn "A CA X.509 certificate was not provided. Server verification will not be performed in TLS connections"
    elif [[ ! -f "$PGBOUNCER_SERVER_TLS_CA_FILE" ]]; then
        print_validation_error "The server CA X.509 certificate file in the specified path ${PGBOUNCER_SERVER_TLS_CA_FILE} does not exist"
```

Not work properly when the server TLS of the server is disabled, therefore it is necessary to know the value of `PGBOUNCER_SERVER_TLS_SSLMODE`. so the previous change (which was also a contribution) has been maintained.

**Comment by tybritten** [comment]
The problem with the change is the files are optional, not required. So if you want to do `PGBOUNCER_SERVER_TLS_SSLMODE=require` it won't start without the files that are optional

**Comment by Mauraza** [comment]
Hi @tybritten ,

What do you thing about this 🔽 ?
```bash
 if [[ "$PGBOUNCER_SERVER_TLS_SSLMODE" != "disable" ]]; then 
     if [[ -z "$PGBOUNCER_SERVER_TLS_CERT_FILE" ]]; then 
         warn "You must provide a X.509 certificate in order to use server TLS" 
     elif [[ ! -f "$PGBOUNCER_SERVER_TLS_CERT_FILE" ]]; then 
         print_validation_error "The X.509 server certificate file in the specified path ${PGBOUNCER_SERVER_TLS_CERT_FILE} does not exist" 
     fi 
     if [[ -z "$PGBOUNCER_SERVER_TLS_KEY_FILE" ]]; then 
         warn "You must provide a private key in order to use server TLS" 
     elif [[ ! -f "$PGBOUNCER_SERVER_TLS_KEY_FILE" ]]; then 
         print_validation_error "The server private key file in the specified path ${PGBOUNCER_SERVER_TLS_KEY_FILE} does not exist" 
     fi 
     if [[ -z "$PGBOUNCER_SERVER_TLS_CA_FILE" ]]; then 
         warn "A CA X.509 certificate was not provided. Server verification will not be performed in TLS connections" 
     elif [[ ! -f "$PGBOUNCER_SERVER_TLS_CA_FILE" ]]; then 
         print_validation_error "The server CA X.509 certificate file in the specified path ${PGBOUNCER_SERVER_TLS_CA_FILE} does not exist" 
     fi 
 fi 
```

**Comment by tybritten** [comment]
If I just want to set `PGBOUNCER_SERVER_TLS_SSLMODE` to `require` without supplying any certs (as they are optional) it won't work with this config. If you want to combine this with my changes, it would look like
```
 if [[ "$PGBOUNCER_SERVER_TLS_SSLMODE" != "disable" ]]; then 
      if [[ -n "$PGBOUNCER_SERVER_TLS_CERT_FILE" ]] && [[ ! -f "$PGBOUNCER_SERVER_TLS_CERT_FILE" ]]; then
           print_validation_error "The X.509 server certificate file in the specified path ${PGBOUNCER_SERVER_TLS_CERT_FILE} does not exist"
       fi
       if [[ -n "$PGBOUNCER_SERVER_TLS_KEY_FILE" ]] && [[ ! -f "$PGBOUNCER_SERVER_TLS_KEY_FILE" ]]; then
           print_validation_error "The server private key file in the specified path ${PGBOUNCER_SERVER_TLS_KEY_FILE} does not exist"
       fi
       if [[ -n "$PGBOUNCER_SERVER_TLS_CA_FILE" ]]; then
           warn "A CA X.509 certificate was not provided. Server verification will not be performed in TLS connections"
       elif [[ ! -f "$PGBOUNCER_SERVER_TLS_CA_FILE" ]]; then
           print_validation_error "The server CA X.509 certificate file in the specified path ${PGBOUNCER_SERVER_TLS_CA_FILE} does not exist"
       fi
fi
```

This would work

**Comment by Mauraza** [comment]
Hi @tybritten,

I will test it and update the thread with the results, but I think you are right and that will work. 

Thanks!!

**Comment by tybritten** [comment]
any luck?

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the long delay, this issue was solved but we didn't come back to you.
  Could you give a try to the latest versions of the container ?
