### ISSUE TITLE
PAM support?

### ISSUE THREAD

**Issue by Anton-Shutik** [bitnami/bitnami-docker-pgbouncer#23]
Does this image has PAM auth support ?
From what I found in [pgbouncer docs](https://github.com/pgbouncer/pgbouncer/#pam-authentication) it has to be built with `--with-pam` flag in order to support PAM auth. Looks like this iamge does not do that ?

**Comment by carrodher** [comment]
pgbouncer is being compiled with the `--with-pam` flag, what's the exact issue you are finding?

**Comment by Anton-Shutik** [comment]
Just didn't find that it's being complied with the `--with-pam` flag.

**Comment by javsalgar** [comment]
Hi,

Please let us know if you find any issue when using this feature, as we are adding the --with-pam flag to the compilation.
