### ISSUE TITLE
Deploy PgBouncer in Kubernetes

### ISSUE THREAD

**Issue by machadovilaca** [bitnami/bitnami-docker-pgbouncer#3]
Since [Bitnami Thanos Chart GitHub repository](https://github.com/bitnami/charts/tree/master/bitnami/pgbouncer), stated in the [README.md](https://github.com/bitnami/bitnami-docker-pgbouncer/blob/master/README.md#how-to-deploy-pgbouncer-in-kubernetes), is no longer available, how do you recommend deploying PgBouncer in Kubernetes?

**Comment by migruiz4** [comment]
Hi @machadovilaca ,

I'm sorry for the misunderstanding, the mention to the Thanos chart in the README is a typo.

The Helm chart the link redirects to doesn't exist either, but we have a chart to deploy PostgreSQL-HA which including Pgpool-II: https://github.com/bitnami/charts/tree/master/bitnami/postgresql-ha

I understand it is not exactly what you asked for, but I'd recommend having a look in case it helps you.

Sorry for the inconvenience.
