### ISSUE TITLE
how to check pgbouncer stats?

### ISSUE THREAD

**Issue by fahadshery** [bitnami/bitnami-docker-pgbouncer#30]
Hi,

I have setup the `bitnami/pgbouncer` using the following:
```bash
 image: 'bitnami/pgbouncer:latest'
    ports:
      - '6432:6432'
    volumes:
      - /path/to/pgbouncer-persistence/conf/:/bitnami/pgbouncer/conf/
    environment:
      - POSTGRESQL_HOST=1.2.3.4
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=mydb
      - POSTGRESQL_USERNAME=myuser
      - POSTGRESQL_PASSWORD=mypass
```

I can connect to my instance using pgbouncer with no issues.
How do I start collecting metrics for `pgbouncer` in the default `pgbouncer db` that come with it?

**Comment by juan131** [comment]
Hi @fahadshery 

It seems it is not an issue related to the Bitnami Pgbouncer container image but about how use the application.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
