### ISSUE TITLE
Delete and Create Volume File on restart 

### ISSUE THREAD

**Issue by amirbayan** [bitnami/bitnami-docker-pgbouncer#32]
### Name and Version

bitnami/pgbouncer:latest

### What steps will reproduce the bug?

1- run the bellow command 
```
docker run --detach --name pgbouncer     -v /data/docker/pgbouncer/pgbouncer-persistence/conf/:/opt//bitnami/pgbouncer/conf/     -p 6432:6432     --env-file  /data/config/pgbouncer-env.list     bitnami/pgbouncer:latest
```

### What is the expected behavior?

I must be able to change the user list.txt content and then on restart pgbouncer must add the new users 

### What do you see instead?

pgbouncer delete userList.txt every time I restart the container

**Comment by javsalgar** [comment]
Hi,

Did you try using custom init scripts to add the users you require?

https://github.com/bitnami/bitnami-docker-pgbouncer/blob/master/1/debian-10/rootfs/opt/bitnami/scripts/libpgbouncer.sh#L276

**Comment by amirbayan** [comment]
Hello, 

No I did not try this method, how can I try it?

**Comment by javsalgar** [comment]
Mount your files in 

```
/docker-entrypoint-initdb.d
```

**Comment by amirbayan** [comment]
Hello @javsalgar ,

I was able to solve the issue be removing the volume for the conf directory (/opt/bitnami/pgbouncer/conf) and adding the init script volume : 

`-v /data/docker/pgbouncer/pgbouncer-persistence/scripts:/docker-entrypoint-initdb.d `

below you will find the init script if anyone faced the same issue: 

```bash
 echo "Init Script for PGBouncer to add users"
 echo "\"username\"  \"password\"" >> /opt/bitnami/pgbouncer/conf/userlist.txt

 echo "Printing userlist.txt content after adding the users:"
 cat /opt/bitnami/pgbouncer/conf/userlist.txt
```

**Comment by javsalgar** [comment]
Awesome! Thanks for sharing! :D
