### ISSUE TITLE
Pgbouncer: Cannot get system entropy

### ISSUE THREAD

**Issue by chungonion** [bitnami/bitnami-docker-pgbouncer#35]
### Name and Version

bitnami/pgbouncer:1.17

### What steps will reproduce the bug?

I deployed the image on Synology's NAS via its' docker package.

Basically, when I started the container, it started normally. When there are some connection attempt, it will shutdown itself and the log has output `pgbouncer: Cannot get system entropy`

### What is the expected behavior?

Connection successfully established 

### What do you see instead?

Log file saying: `pgbouncer: Cannot get system entropy`

### Additional information

I notice  [someone](https://github.com/edoburu/docker-pgbouncer/issues/54) mentioned this issue on another pgbouncer image, however, there was no further information being given to determine the cause.

**Comment by carrodher** [comment]
It seems it is not an issue related to the Bitnami pgbouncer container image or Helm chart but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, we will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.

**Comment by chungonion** [comment]
> 

Okay... I was curious whether the image/docker hosting environment _might_ have barred the container from access the entropy. Thanks anyway~
