### ISSUE TITLE
No option to set `ignore_startup_parameters` via environment variable

### ISSUE THREAD

**Issue by somesocks** [bitnami/bitnami-docker-pgbouncer#6]
I'd like to use this image as a proxy for an application database, but some of the tools I'd like to use have newer PG JDBC connectors, which causes pgbouncer to throw an error.  See https://github.com/dbeaver/dbeaver/issues/2361 for more details.

I like how the startup scripts auto-generate `pgbouncer.ini` from the environment variables, it's very useful to provide those from the k8s or docker-compose cluster.  Unfortunately, the bitnami scripts turn off auto-generation if you provide a custom `pgbouncer.ini`.

So, it'd be nice to also expose `ignore_startup_parameters` as an environment variable, so that people could fix issues like these without having to build a custom docker image on top of this one, or provide a completely custom `pgbouncer.ini`

**Comment by pablogalegoc** [comment]
Hi @somesocks! I see you've already opened a PR, thank you for your contribution!
